# Generated by Django 3.2 on 2021-06-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='descriptio',
            new_name='description',
        ),
    ]
